on: push
name: CI

jobs:
  build:
    uses: BattletechModders/ModTek/.github/workflows/mod-builder.yml@master
    with:
      checkout-directory: 'BATTLETECH/Mods/SpeedMod'
      build-script: |
        (
          cd source
          dotnet build -c Release -p:BattleTechGameDir="$BATTLETECH_DIR/"
        )
        (
          cd ..
          7z a -tzip -mx9 "$DIST_DIR/SpeedMod.zip" \
            -ir!SpeedMod \
            -xr!source "-xr!.*"
        )
      release-notes: |
        Works best with ModTek V3
        - SpeedMod.zip contains the mod
    secrets: inherit
